name: ML Churn Prototype
description: Prototype to demonstrate building a churn model on CML
author: Cloudera Inc.
specification_version: 1.0
prototype_version: 3.0
date: "2024-05-29"

environment_variables:
  DATA_LOCATION:
    default: data/churn_prototype
    description: >-
      Relative path that will be used to store the data used for this prototype.
      This should be a location you have write access to, and which is suitable for non-production data.
  HIVE_DATABASE:
    default: default
    description: >-
      Name of the Hive database that will be used to create the Hive table used for this prototype.
      This should be a Hive database you have write access to, and which is suitable for non-production data.
  HIVE_TABLE:
    default: churn_prototype
    description: >-
      Name of the Hive table that will be created and populated with the data used for this prototype.
      If the table already exists, the prototype will assume it already contains the data for this prototype.
      
  ADLS_CONECTION_STRING:
    default:
    description: >-
      Full connection string to connect to ADLS Gen2 storage account
      
  STORAGE_MODE:
    default: external
    description: >-
      external to use HDFS and Hive tables, internal to use local project files

feature_dependencies:
  - model_metrics

runtimes:
  - editor: Workbench
    kernel: Python 3.9
    edition: Standard
    addons: ["Spark 3.2.3 - CDP 7.1.7.2035"]

tasks:
  - type: run_session
    name: Install dependencies
    script: code/0_bootstrap.py
    short_summary: >-
      Install dependencies, set environment variables, and upload data.
    cpu: 1
    memory: 2
    
  - type: run_session
    name: Ingest data
    script: code/1_data_ingest.py
    short_summary: >-
      Create hive table in the datalake and use uploaded data as source.
    cpu: 1
    memory: 2
